# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_details_pb2 as grpc__details__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_details_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class lab6serviceStub(object):
    """Service Interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.doAdd = channel.unary_unary(
                '/lab6service.lab6service/doAdd',
                request_serializer=grpc__details__pb2.addNumbersReq.SerializeToString,
                response_deserializer=grpc__details__pb2.addition.FromString,
                _registered_method=True)
        self.doDotProduct = channel.unary_unary(
                '/lab6service.lab6service/doDotProduct',
                request_serializer=grpc__details__pb2.dotProductReq.SerializeToString,
                response_deserializer=grpc__details__pb2.dotProduct.FromString,
                _registered_method=True)
        self.doRawImage = channel.unary_unary(
                '/lab6service.lab6service/doRawImage',
                request_serializer=grpc__details__pb2.rawImageReq.SerializeToString,
                response_deserializer=grpc__details__pb2.rawImageDims.FromString,
                _registered_method=True)
        self.doJsonImage = channel.unary_unary(
                '/lab6service.lab6service/doJsonImage',
                request_serializer=grpc__details__pb2.rawJsonReq.SerializeToString,
                response_deserializer=grpc__details__pb2.jsonImageDims.FromString,
                _registered_method=True)


class lab6serviceServicer(object):
    """Service Interface
    """

    def doAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doDotProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doRawImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doJsonImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_lab6serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'doAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.doAdd,
                    request_deserializer=grpc__details__pb2.addNumbersReq.FromString,
                    response_serializer=grpc__details__pb2.addition.SerializeToString,
            ),
            'doDotProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.doDotProduct,
                    request_deserializer=grpc__details__pb2.dotProductReq.FromString,
                    response_serializer=grpc__details__pb2.dotProduct.SerializeToString,
            ),
            'doRawImage': grpc.unary_unary_rpc_method_handler(
                    servicer.doRawImage,
                    request_deserializer=grpc__details__pb2.rawImageReq.FromString,
                    response_serializer=grpc__details__pb2.rawImageDims.SerializeToString,
            ),
            'doJsonImage': grpc.unary_unary_rpc_method_handler(
                    servicer.doJsonImage,
                    request_deserializer=grpc__details__pb2.rawJsonReq.FromString,
                    response_serializer=grpc__details__pb2.jsonImageDims.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lab6service.lab6service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lab6service.lab6service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class lab6service(object):
    """Service Interface
    """

    @staticmethod
    def doAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab6service.lab6service/doAdd',
            grpc__details__pb2.addNumbersReq.SerializeToString,
            grpc__details__pb2.addition.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doDotProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab6service.lab6service/doDotProduct',
            grpc__details__pb2.dotProductReq.SerializeToString,
            grpc__details__pb2.dotProduct.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doRawImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab6service.lab6service/doRawImage',
            grpc__details__pb2.rawImageReq.SerializeToString,
            grpc__details__pb2.rawImageDims.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doJsonImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lab6service.lab6service/doJsonImage',
            grpc__details__pb2.rawJsonReq.SerializeToString,
            grpc__details__pb2.jsonImageDims.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
