# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc-details.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'grpc-details.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12grpc-details.proto\x12\x0blab6service\"+\n\raddNumbersReq\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1a\n\x0brawImageReq\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"\x1f\n\nrawJsonReq\x12\x11\n\timgString\x18\x01 \x01(\t\"+\n\rdotProductReq\x12\x0c\n\x04num1\x18\x01 \x03(\x02\x12\x0c\n\x04num2\x18\x02 \x03(\x02\"\x17\n\x08\x61\x64\x64ition\x12\x0b\n\x03sum\x18\x01 \x01(\x05\" \n\ndotProduct\x12\x12\n\ndotProduct\x18\x01 \x01(\x02\"-\n\x0crawImageDims\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\".\n\rjsonImageDims\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\x9d\x02\n\x0blab6service\x12<\n\x05\x64oAdd\x12\x1a.lab6service.addNumbersReq\x1a\x15.lab6service.addition\"\x00\x12\x45\n\x0c\x64oDotProduct\x12\x1a.lab6service.dotProductReq\x1a\x17.lab6service.dotProduct\"\x00\x12\x43\n\ndoRawImage\x12\x18.lab6service.rawImageReq\x1a\x19.lab6service.rawImageDims\"\x00\x12\x44\n\x0b\x64oJsonImage\x12\x17.lab6service.rawJsonReq\x1a\x1a.lab6service.jsonImageDims\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_details_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDNUMBERSREQ']._serialized_start=35
  _globals['_ADDNUMBERSREQ']._serialized_end=78
  _globals['_RAWIMAGEREQ']._serialized_start=80
  _globals['_RAWIMAGEREQ']._serialized_end=106
  _globals['_RAWJSONREQ']._serialized_start=108
  _globals['_RAWJSONREQ']._serialized_end=139
  _globals['_DOTPRODUCTREQ']._serialized_start=141
  _globals['_DOTPRODUCTREQ']._serialized_end=184
  _globals['_ADDITION']._serialized_start=186
  _globals['_ADDITION']._serialized_end=209
  _globals['_DOTPRODUCT']._serialized_start=211
  _globals['_DOTPRODUCT']._serialized_end=243
  _globals['_RAWIMAGEDIMS']._serialized_start=245
  _globals['_RAWIMAGEDIMS']._serialized_end=290
  _globals['_JSONIMAGEDIMS']._serialized_start=292
  _globals['_JSONIMAGEDIMS']._serialized_end=338
  _globals['_LAB6SERVICE']._serialized_start=341
  _globals['_LAB6SERVICE']._serialized_end=626
# @@protoc_insertion_point(module_scope)
